#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MSG=$(cat "${1:?Missing commit message file}")

COMMIT_TYPE="${COMMIT_MSG%%:*}"

if [[ "${COMMIT_TYPE}" == *"test"* ]]; then
  yarn test
fi  

npx --no -- commitlint --edit "$1"
